# Generated by Django 2.2.5 on 2020-01-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_auto_20200113_0316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movielist',
        ),
    ]
