# Generated by Django 2.2.5 on 2020-01-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_auto_20200113_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='poster',
            field=models.ImageField(upload_to='movie_poster'),
        ),
    ]
